# Generated by Django 3.0.4 on 2020-04-24 08:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('floor', models.IntegerField()),
                ('slot', models.IntegerField()),
                ('transaction_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'booking_list',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.CharField(max_length=100)),
                ('license_plate', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField()),
                ('datetime', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
