# Generated by Django 3.0.4 on 2020-04-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezpark', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('floor', models.IntegerField()),
                ('slot', models.IntegerField()),
            ],
            options={
                'db_table': 'ezpark_mall',
            },
        ),
    ]
